web/router.ex
defmodule Elide.Router do
  use Elide.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Elide.Auth, repo: Elide.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ui do
    plug :put_layout, {Elide.UiLayoutView, "app.html"}
  end

  scope "/", Elide do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/:slug", ElinkController, :go
  end

  scope "/ui", Elide do
    pipe_through [:browser, :authenticate_user, :ui]
    resources "/org", OrganizationController do
      resources "/members", MembershipController
    end
    resources "/elinks", ElinkController
    resources "/tokens", TokenController
  end

  scope "/users/auth", Elide do
    pipe_through :browser

    get "/:provider", UserController, :provider
    get "/:provider/callback", UserController, :callback
    #delete "/logout", AuthController, :delete
  end

  scope "/api", Elide do
    pipe_through :api
    scope "/v1", V1 do
      post "/elinks", ElinkApiController, :create
    end
  end
end

web/views/uilayout_view.ex
defmodule Elide.UiLayoutView do
  use Elide.Web, :view
end

web/templates/ui_layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elide Internal!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div id="wrapper" class="elide-mem-ui">

            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <%= link "Home", to: page_path(@conn, :index) %>
                    </li>
                    <li>
                        <%= link "Links", to: elink_path(@conn, :index) %>
                    </li>
                    <li>
                      <h3>Organization</h3>
                    </li>
                    <li>
                        <%= link "Organization", to: organization_path(@conn, :index) %>
                    </li>
                    <li>
                      <h3>Settings</h3>
                    </li>
                    <li>
                        <%= link "Access tokens", to: token_path(@conn, :index) %>
                    </li>

                </ul>
            </div>
            <!-- /#sidebar-wrapper -->

            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                        <%= render @view_module, @view_template, assigns %>
                  </div>

              </div>
          </div>
      </div>

    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>